// Code generated by hikec. DO NOT EDIT.
package fizzlib

import "unsafe"

// GetFizzFileSize: ファイルサイズ取得
func GetFizzFileSize(filename string) int {
	return _hike_GetFizzFileSize(filename)
}

// ReadFizzFile: バッファへの書き込み（ジャストサイズスライス返却）
func ReadFizzFile(filename string, readSize int, buf []byte) []byte {
	if len(buf) == 0 || readSize <= 0 {
		return buf[:0]
	}

	targetSize := readSize
	if targetSize > len(buf) {
		targetSize = len(buf)
	}

	// unsafe.SliceData でバッファ先頭アドレスを渡し、書き込みサイズを受け取る
	written := _hike_ReadFizzFile(filename, targetSize, unsafe.SliceData(buf))
	if written < 0 {
		return buf[:0]
	}
	if written > len(buf) {
		written = len(buf)
	}

	return buf[:written]
}

// GetMetaData: Cで動的確保された文字列をGo文字列として取得
func GetMetaData(filename string) string {
	var cLen int
	cPtr := _hike_GetMetaData(filename, &cLen)
	if cPtr == nil || cLen == 0 {
		return ""
	}

	temp := unsafe.String((*byte)(cPtr), cLen)
	res := string(temp)
	_hike_free(cPtr)

	return res
}

// -----------------------------------------------------------------------------
// ネイティブリンク宣言（stub.s のアセンブリを経由して .syso と結合）
// -----------------------------------------------------------------------------
func _hike_GetFizzFileSize(filename string) int
func _hike_ReadFizzFile(filename string, readSize int, bufPtr *byte) int
func _hike_GetMetaData(filename string, outLen *int) unsafe.Pointer
func _hike_free(ptr unsafe.Pointer)
