/**
 * Hike Language Unified WebAssembly Runtime (runtime.js)
 * Auto-generated by hikec - Supports the Main Thread context.
 */

// モジュールスコープ変数: WASMが要求するヒープメモリサイズ (KB単位)
let heapSizeKB = 256;

// =============================================================================
// 2. メインスレッド コンテキスト (ブラウザ DOM / クライアント側)
// =============================================================================
// Keep the same runtime usable from browser pages and Node-based E2E tests.
// Node does not define window, but it can still load the generated runtime
// through CommonJS.
if (typeof window !== 'undefined' || (typeof module !== 'undefined' && module.exports)) {
    // Lightweight main-thread runtime. Application-specific host functions
    // are injected from jfunc declarations in the Hike source program.
    class HikeRuntime {
        constructor(options = {}) {
            this.wasmUrl = options.wasmUrl || 'main.wasm';
            this.instance = null;
            this.memory = null;
            this.onLog = options.onLog || (() => {});
            this.onFrame = options.onFrame || (() => {});
            this.frame = 0;
            this.frameCount = 0;
        }

        log(event, details = {}) {
            this.onLog(event, details);
        }

        readString(value) {
            const view = new DataView(this.memory.buffer);
            const object = Number(value);
            const size = this.memory.buffer.byteLength;
            const bytes = new Uint8Array(this.memory.buffer);
            // WAT emitted by the compiler is returned as a raw C string. Check
            // its opening byte before interpreting the pointer as a Hike
            // string object; otherwise the first four text bytes can look like
            // a plausible object header.
            if (object >= 0 && object < size && bytes[object] === 0x28) {
                let length = 0;
                while (object + length < size && bytes[object + length] !== 0) length++;
                return new TextDecoder().decode(bytes.slice(object, object + length));
            }
            if (object >= 0 && object + 12 <= size) {
                const data = view.getUint32(object, true);
                const length = view.getUint32(object + 8, true);
                if (data < size && length <= size - data) {
                    return new TextDecoder().decode(new Uint8Array(this.memory.buffer, data, length));
                }
            }
            // Some Go-Hike builder paths return a C-string pointer rather than
            // a packed Hike string object. Accept both ABI forms at jfunc
            // boundaries.
            if (object < 0 || object >= size) return "";
            let length = 0;
            while (object + length < size && bytes[object + length] !== 0) length++;
            return new TextDecoder().decode(bytes.slice(object, object + length));
        }

        readCString(value) {
            const object = Number(value);
            const bytes = new Uint8Array(this.memory.buffer);
            if (object < 0 || object >= bytes.length) return "";
            let length = 0;
            while (object + length < bytes.length && bytes[object + length] !== 0) length++;
            return new TextDecoder().decode(bytes.slice(object, object + length));
        }

        writeString(value) {
            if (this.jfuncHeap === undefined) {
                // Keep JavaScript-owned string objects outside the Hike heap.
                const base = 128 * 1024 * 1024;
                const pages = Math.ceil((base - this.memory.buffer.byteLength) / 65536);
                if (pages > 0) this.memory.grow(pages);
                this.jfuncHeap = base;
            }
            const bytes = new TextEncoder().encode(String(value));
            const data = this.jfuncHeap + 12;
            const object = this.jfuncHeap;
            const required = data + bytes.length + 1;
            while (required > this.memory.buffer.byteLength) this.memory.grow(16);
            new Uint8Array(this.memory.buffer, data, bytes.length).set(bytes);
            new Uint8Array(this.memory.buffer)[data + bytes.length] = 0;
            const view = new DataView(this.memory.buffer);
            view.setUint32(object, data, true);
            view.setUint32(object + 4, 0, true);
            view.setUint32(object + 8, bytes.length, true);
            this.jfuncHeap = data + bytes.length + 1;
            return object;
        }

        imports() {
            const runtime = this;
            const env = {
                malloc: (size) => runtime.malloc(size),
                calloc: (count, size) => {
                    const total = Number(count) * Number(size);
                    const ptr = runtime.malloc(total);
                    new Uint8Array(runtime.memory.buffer, ptr, total).fill(0);
                    return ptr;
                },
                free: () => {},
                // C-style output used by the standard library and compiler
                // bootstrap. Browser examples do not need to render it, but
                // the import must exist for modules that reference printf.
                printf: () => 0,
                memcpy: (dst, src, n) => {
                    const d = new Uint8Array(runtime.memory.buffer, Number(dst), Number(n));
                    const s = new Uint8Array(runtime.memory.buffer, Number(src), Number(n));
                    d.set(s);
                    return Number(dst);
                },
                strlen: (ptr) => {
                    const bytes = new Uint8Array(runtime.memory.buffer);
                    let n = 0;
                    while (bytes[Number(ptr) + n] !== 0) n++;
                    return n;
                },
                memcmp: (a, b, n) => {
                    const bytes = new Uint8Array(runtime.memory.buffer);
                    for (let i = 0; i < Number(n); i++) {
                        const av = bytes[Number(a) + i];
                        const bv = bytes[Number(b) + i];
                        if (av !== bv) return av < bv ? -1 : 1;
                    }
                    return 0;
                },
                sqrt: (x) => Math.sqrt(Number(x)),
                fabs: (x) => Math.abs(Number(x)),
				floor: (x) => Math.floor(Number(x)),
				ceil: (x) => Math.ceil(Number(x)),
                pow: (x, y) => Math.pow(Number(x), Number(y)),
                sin: (x) => Math.sin(Number(x)),
                log2: (x) => Math.log2(Number(x)),
                hike_thread_spawn: (fnIdx, paramPtr) => {
                    const table = runtime.instance && (runtime.instance.exports.__indirect_function_table || runtime.instance.exports.table);
                    const thunk = table && table.get(Number(fnIdx));
                    if (!thunk) return -1;
                    thunk(paramPtr);
                    return 0;
                },
                hike_event_create: () => 1,
                hike_event_signal: () => {},
                hike_event_wait: () => 0,
                hike_event_destroy: () => {},
                hike_sleep_ms: () => {},
                hike_now_ns: () => BigInt(Math.floor(performance.now() * 1000000))
            };
            env["__hike_js_wasm_hikec_source"] = function() {
                const memory = runtime.memory;
                const wasmMemory = runtime.memory;
                runtime.log("jfunc:wasm_hikec_source", { args: Array.from(arguments) });
return runtime . writeString ( globalThis . __hikeWasmC . source || "" ) ; 
            };
            env["__hike_js_wasm_hikec_publish_wat"] = function(wat) {
                const memory = runtime.memory;
                const wasmMemory = runtime.memory;
                runtime.log("jfunc:wasm_hikec_publish_wat", { args: Array.from(arguments) });
globalThis . __hikeWasmC . wat = runtime . readString ( wat ) ; return wat . length ; 
            };
            env["__hike_js_wasm_hikec_runtime_init"] = function() {
                const memory = runtime.memory;
                const wasmMemory = runtime.memory;
                runtime.log("jfunc:wasm_hikec_runtime_init", { args: Array.from(arguments) });
if ( ! globalThis . __hikeWasmC ) { globalThis . __hikeWasmC = { } ; } ; globalThis . __hikeWasmC . memory = wasmMemory ; return 1 ; 
            };
            env["__hike_js_wasm_hikec_echo_source_enabled"] = function() {
                const memory = runtime.memory;
                const wasmMemory = runtime.memory;
                runtime.log("jfunc:wasm_hikec_echo_source_enabled", { args: Array.from(arguments) });
if ( globalThis . __hikeWasmC . echoSource ) { return 1 } ; return 0 ; 
            };
            env["__hike_js_wasm_hikec_debug_phase"] = function(phase) {
                const memory = runtime.memory;
                const wasmMemory = runtime.memory;
                runtime.log("jfunc:wasm_hikec_debug_phase", { args: Array.from(arguments) });
globalThis . __hikeWasmC . debugPhase = phase ; runtime . log ( "debug-phase" , { phase } ) ; return phase ; 
            };

            return { env };
        }

        malloc(size) {
            if (this.heap === undefined) {
                const base = this.instance && this.instance.exports.__heap_base;
                this.heap = base ? Number(base.value || base) : 65536;
            }
            const ptr = this.heap;
            this.heap += (Number(size) + 15) & ~15;
            if (this.instance && this.memory && this.heap > this.memory.buffer.byteLength) {
                const missing = this.heap - this.memory.buffer.byteLength;
                this.memory.grow(Math.ceil(missing / 65536));
            }
            return ptr;
        }

        async load() {
            this.log('wasm-load:begin', { url: this.wasmUrl });
            const response = await fetch(this.wasmUrl);
            if (!response.ok) throw new Error('Failed to fetch ' + this.wasmUrl + ': ' + response.status);
            this.log('wasm-load:response', { ok: response.ok, status: response.status, contentLength: response.headers.get('content-length') });
            const bytes = await response.arrayBuffer();
            this.log('wasm-load:bytes', { byteLength: bytes.byteLength });
            const memory = new WebAssembly.Memory({ initial: 2, maximum: 256 });
            const imports = this.imports();
            imports.env.memory = memory;
            const result = await WebAssembly.instantiate(bytes, imports);
            this.instance = result.instance;
            this.memory = this.instance.exports.memory || memory;
            this.log('WebAssembly.instantiate:returned', {
                exports: Object.keys(this.instance.exports),
                imports: WebAssembly.Module.imports(await WebAssembly.compile(bytes)).map((item) => item.name)
            });
            this.log('wasm-memory:ready', { byteLength: this.memory.buffer.byteLength });
            if (typeof this.instance.exports.InitApp === 'function') {
                this.log('wasm.exports.InitApp:begin', {});
                this.instance.exports.InitApp();
                this.log('wasm.exports.InitApp:return', {});
            }
            if (typeof this.instance.exports.RenderFrame === 'function') {
                const draw = (time) => {
                    if (this.instance) {
                        const angle = time / 1000;
                        const frame = ++this.frameCount;
                        this.onFrame({ frame, time, angle });
                        this.instance.exports.RenderFrame(angle);
                    }
                    this.frame = requestAnimationFrame(draw);
                };
                this.frame = requestAnimationFrame(draw);
            }
            return this.instance.exports;
        }

        stop() {
            if (this.frame) cancelAnimationFrame(this.frame);
            this.frame = 0;
        }
    }

    if (typeof window !== 'undefined') window.HikeRuntime = HikeRuntime;

    class HikeConcurrentRuntime {
        /**
         * @param {Object} options
         * @param {string} [options.wasmUrl='main.wasm']
         * @param {string} [options.scriptUrl='runtime.js'] - 自身のスクリプトファイルパス
         * @param {number} [options.heapSizeKB=256]
         * @param {Function} [options.onResult]
         * @param {Function} [options.onLog]
         */
        constructor(options = {}) {
            this.wasmUrl = options.wasmUrl || 'main.wasm';
            this.scriptUrl = options.scriptUrl || 'runtime.js';
            this.heapSizeKB = options.heapSizeKB || 256;
            this.onResult = options.onResult || (() => {});
            this.onLog = options.onLog || (() => {});
            this.worker = null;
            this.memory = null;
            globalThis.__hikeActiveRuntime = this;
        }

        /**
         * 外部からヒープサイズを変更するAPI
         */
        setHeapSizeKB(sizeKB) {
            this.heapSizeKB = Number(sizeKB);
            if (this.worker) {
                this.worker.postMessage({ type: 'setHeapSizeKB', sizeKB: this.heapSizeKB });
            }
        }

        getHeapSizeKB() {
            return this.heapSizeKB;
        }

        /**
         * runtime.js 自身を Worker として起動
         */
        async start() {
            this.onLog('Hike Concurrent Engine (runtime.js) を起動中...');

            // runtime.js 自体を Worker スレッドとしてインスタンス化
            this.worker = new Worker(this.scriptUrl + '?t=' + Date.now());

            this.worker.onmessage = (e) => {
                const { type, sum, mul, message } = e.data;
                if (type === 'log') {
                    this.onLog(message);
                } else if (type === 'result') {
                    this.onResult(sum, mul);
                }
            };

            this.memory = new WebAssembly.Memory({
                initial: 256,
                maximum: 512,
                shared: true
            });

            const res = await fetch(this.wasmUrl);
            if (!res.ok) {
                throw new Error(`Failed to fetch WASM: ${res.statusText}`);
            }
            const wasmBytes = await res.arrayBuffer();

            this.worker.postMessage({
                type: 'init',
                wasmBytes: wasmBytes,
                memory: this.memory,
                heapSizeKB: this.heapSizeKB
            });
        }

        terminate() {
            if (this.worker) {
                this.worker.terminate();
                this.worker = null;
            }
        }
    }

    // グローバル公開API
    if (typeof window !== 'undefined') window.HikeConcurrentRuntime = HikeConcurrentRuntime;
    globalThis.setHikeHeapSizeKB = (sizeKB) => {
        heapSizeKB = Number(sizeKB);
        if (globalThis.__hikeActiveRuntime) {
            globalThis.__hikeActiveRuntime.setHeapSizeKB(heapSizeKB);
        }
    };
    globalThis.getHikeHeapSizeKB = () => heapSizeKB;

    if (typeof module !== 'undefined' && module.exports) {
        module.exports = { HikeRuntime, HikeConcurrentRuntime };
    }
}
	