package compiler

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"

	"hikec-go/pkg/ast"
)

// GenerateGoDeclarations は *.go.hike から Go コンパイラ用の *.go ラッパー・宣言ファイルを生成します。
func GenerateGoDeclarations(destGoPath string, pkgName string, decls []ast.Decl, verbose bool) error {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by hikec. DO NOT EDIT.\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkgName))

	needsUnsafe := true // SliceData, String, unsafe.Pointer 等で基本的に必要
	var wrapperFuncs []string
	var nativeDecls []string

	// CFuncDecl のみを抽出
	var cfuncs []*ast.CFuncDecl
	for _, decl := range decls {
		if cfn, ok := decl.(*ast.CFuncDecl); ok {
			cfuncs = append(cfuncs, cfn)
		}
	}

	// 1. 公開 Go ラッパー関数の生成（大文字始まりのエクスポート関数のみ）
	for _, cfn := range cfuncs {
		fnName := cfn.Name.Value
		if !isExported(fnName) {
			continue
		}

		wrapper := generateWrapperFunc(cfn)
		if wrapper != "" {
			wrapperFuncs = append(wrapperFuncs, wrapper)
		}
	}

	// 2. ネイティブリンク宣言の生成（stub.s 結合用）
	for _, cfn := range cfuncs {
		nativeDecl := generateNativeDecl(cfn)
		nativeDecls = append(nativeDecls, nativeDecl)
	}

	if needsUnsafe {
		buf.WriteString("import \"unsafe\"\n\n")
	}

	// ラッパー関数群の出力
	for _, w := range wrapperFuncs {
		buf.WriteString(w + "\n")
	}

	// ネイティブ宣言群の出力
	buf.WriteString("// -----------------------------------------------------------------------------\n")
	buf.WriteString("// ネイティブリンク宣言（stub.s のアセンブリを経由して .syso と結合）\n")
	buf.WriteString("// -----------------------------------------------------------------------------\n")
	for _, nd := range nativeDecls {
		buf.WriteString(nd + "\n")
	}

	if verbose {
		fmt.Printf("[hikec go] Emitting Go declarations -> %s\n", filepath.Base(destGoPath))
	}

	return os.WriteFile(destGoPath, buf.Bytes(), 0644)
}

// generateWrapperFunc は CFuncDecl から Go フレンドリーなラッパー関数を合成します。
func generateWrapperFunc(cfn *ast.CFuncDecl) string {
	fnName := cfn.Name.Value
	hasCStringRet := len(cfn.ReturnTypes) == 1 && isCStringType(cfn.ReturnTypes[0])
	hasOutLen := false
	for _, p := range cfn.Params {
		if p.Name.Value == "outLen" || (isPointerType(p.Type) && strings.Contains(p.Name.Value, "Len")) {
			hasOutLen = true
			break
		}
	}

	hasBuf := false
	hasSize := false
	for _, p := range cfn.Params {
		if p.Name.Value == "buf" && isPointerType(p.Type) {
			hasBuf = true
		}
		if strings.Contains(strings.ToLower(p.Name.Value), "size") && isIntType(p.Type) {
			hasSize = true
		}
	}

	// パターン 1: 動的文字列返却（GetMetaData 等）
	if hasCStringRet && hasOutLen {
		return fmt.Sprintf(`// %s: Cで動的確保された文字列をGo文字列として取得
func %s(filename string) string {
	var cLen int
	cPtr := _hike_%s(filename, &cLen)
	if cPtr == nil || cLen == 0 {
		return ""
	}

	temp := unsafe.String((*byte)(cPtr), cLen)
	res := string(temp)
	_hike_free(cPtr)

	return res
}
`, fnName, fnName, fnName)
	}

	// パターン 2: スライスバッファ書き込み（ReadFizzFile 等）
	if hasBuf && hasSize {
		return fmt.Sprintf(`// %s: バッファへの書き込み（ジャストサイズスライス返却）
func %s(filename string, readSize int, buf []byte) []byte {
	if len(buf) == 0 || readSize <= 0 {
		return buf[:0]
	}

	targetSize := readSize
	if targetSize > len(buf) {
		targetSize = len(buf)
	}

	// unsafe.SliceData でバッファ先頭アドレスを渡し、書き込みサイズを受け取る
	written := _hike_%s(filename, targetSize, unsafe.SliceData(buf))
	if written < 0 {
		return buf[:0]
	}
	if written > len(buf) {
		written = len(buf)
	}

	return buf[:written]
}
`, fnName, fnName, fnName)
	}

	// パターン 3: 通常呼出（GetFizzFileSize 等）
	comment := "ファイルサイズ取得"
	if fnName != "GetFizzFileSize" {
		comment = "ネイティブ関数呼出"
	}
	return fmt.Sprintf(`// %s: %s
func %s(filename string) int {
	return _hike_%s(filename)
}
`, fnName, comment, fnName, fnName)
}

// generateNativeDecl は stub.s 接続用の _hike_xxx 宣言を合成します。
func generateNativeDecl(cfn *ast.CFuncDecl) string {
	fnName := cfn.Name.Value
	var params []string

	for i := 0; i < len(cfn.Params); i++ {
		p := cfn.Params[i]

		// (cstring, int) ペアは Go 側で string 1 つとして宣言
		if isCStringType(p.Type) && i+1 < len(cfn.Params) && isIntType(cfn.Params[i+1].Type) {
			paramName := strings.TrimSuffix(p.Name.Value, "_ptr")
			if paramName == "fn" {
				paramName = "filename"
			}
			params = append(params, fmt.Sprintf("%s string", paramName))
			i++
			continue
		}

		if p.Name.Value == "buf" && isPointerType(p.Type) {
			params = append(params, "bufPtr *byte")
			continue
		}

		if fnName == "free" && isPointerType(p.Type) {
			params = append(params, "ptr unsafe.Pointer")
			continue
		}

		goType, _ := typeExprToGoType(p.Type, false)
		params = append(params, fmt.Sprintf("%s %s", p.Name.Value, goType))
	}

	resStr := ""
	if len(cfn.ReturnTypes) == 1 {
		goRet, _ := typeExprToGoType(cfn.ReturnTypes[0], true)
		resStr = " " + goRet
	} else if len(cfn.ReturnTypes) > 1 {
		var rets []string
		for _, rt := range cfn.ReturnTypes {
			t, _ := typeExprToGoType(rt, true)
			rets = append(rets, t)
		}
		resStr = " (" + strings.Join(rets, ", ") + ")"
	}

	return fmt.Sprintf("func _hike_%s(%s)%s", fnName, strings.Join(params, ", "), resStr)
}

func isExported(name string) bool {
	if len(name) == 0 {
		return false
	}
	return unicode.IsUpper(rune(name[0]))
}

func isPointerType(te ast.TypeExpr) bool {
	if te == nil {
		return false
	}
	_, ok := te.(*ast.PointerType)
	return ok || strings.HasPrefix(te.TokenLiteral(), "*")
}

func isCStringType(te ast.TypeExpr) bool {
	if te == nil {
		return false
	}
	if nt, ok := te.(*ast.NamedType); ok {
		return nt.Name.Value == "cstring"
	}
	return te.TokenLiteral() == "cstring"
}

func isIntType(te ast.TypeExpr) bool {
	if te == nil {
		return false
	}
	if nt, ok := te.(*ast.NamedType); ok {
		return nt.Name.Value == "int"
	}
	return te.TokenLiteral() == "int"
}

func typeExprToGoType(te ast.TypeExpr, isReturn bool) (string, bool) {
	if te == nil {
		return "", false
	}

	switch t := te.(type) {
	case *ast.NamedType:
		name := t.Name.Value
		if name == "cstring" {
			if isReturn {
				return "unsafe.Pointer", true
			}
			return "string", false
		}
		return name, false

	case *ast.PointerType:
		baseName, isUnsafe := typeExprToGoType(t.Base, isReturn)
		if baseName == "void" {
			return "unsafe.Pointer", true
		}
		return "*" + baseName, isUnsafe

	default:
		lit := te.TokenLiteral()
		if lit == "cstring" {
			if isReturn {
				return "unsafe.Pointer", true
			}
			return "string", false
		}
		return lit, false
	}
}
