package compiler

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"hikec-go/pkg/target"
)

// TestGoHikeMapCompositeValueDoesNotEmitAnonymousStruct reproduces the invalid
// LLVM generated by the composite-value boxing path. The self-hosted loader
// reaches the same path through map[string][]ast.Decl; this smaller input
// isolates the anonymous-struct type rendering without loading the whole
// compiler dependency graph.
func TestGoHikeMapCompositeValueDoesNotEmitAnonymousStruct(t *testing.T) {
	root := t.TempDir()
	repoRoot, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	mod := "module map-composite-repro\nhike 0.1.0\n" +
		"GoReplace hikec-go/pkg => " + filepath.ToSlash(filepath.Join(repoRoot, "pkg")) + "\n"
	if err := os.WriteFile(filepath.Join(root, "hike.mod"), []byte(mod), 0644); err != nil {
		t.Fatal(err)
	}

	source := `package main

func main() int {
	values := make(map[string]struct{})
	values["empty"] = struct{}{}
    return 0
}
`
	entry := filepath.Join(root, "main.go")
	if err := os.WriteFile(entry, []byte(source), 0644); err != nil {
		t.Fatal(err)
	}

	tgt := target.TargetX86_64Windows
	c := New(&tgt)
	c.SetGoHikeMode(true)
	ir, _, _, err := c.CompileToLLVM(entry)
	if err != nil {
		t.Fatalf("Go-Hike map composite reproduction failed before IR emission: %v\n%s", err, c.Reporter().FormatAll())
	}
	if strings.Contains(ir, "%struct.*") {
		t.Fatalf("Go-Hike composite map value emitted an anonymous struct type")
	}
}
