package compiler

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"hikec-go/pkg/ast"
)

// GenerateGoStubs は CFuncDecl 群から Plan 9 アセンブリスタブを自動生成します。
func GenerateGoStubs(targetDir string, pkgName string, decls []ast.Decl, verbose bool) error {
	var cfuncs []*ast.CFuncDecl
	for _, d := range decls {
		if cfd, ok := d.(*ast.CFuncDecl); ok {
			cfuncs = append(cfuncs, cfd)
		}
	}
	if len(cfuncs) == 0 {
		return nil
	}

	if verbose {
		fmt.Printf("[hikec go] Generating Plan 9 assembly stubs for %d cfunc(s):\n", len(cfuncs))
		for _, fn := range cfuncs {
			mode := "normal"
			if fn.IsPassThrough {
				mode = "passthrough (NOSPLIT)"
			}
			fmt.Printf("  - %s (%s)\n", fn.Name.Value, mode)
		}
	}

	// Plan 9 アセンブリ (Windows amd64 向け)
	var sBuilder strings.Builder
	sBuilder.WriteString("// Code generated by hikec go. DO NOT EDIT.\n")
	sBuilder.WriteString("#include \"textflag.h\"\n\n")

	// Windows x64 ABI レジスタ順序
	winRegs := []string{"CX", "DX", "R8", "R9"}

	for _, fn := range cfuncs {
		targetCName := "c_" + fn.Name.Value
		if fn.TargetCName != nil {
			targetCName = fn.TargetCName.Value
		}

		argSize := (len(fn.Params) + len(fn.ReturnTypes)) * 8
		textFlag := "0"
		if fn.IsPassThrough {
			textFlag = "NOSPLIT"
		}

		sBuilder.WriteString(fmt.Sprintf("// %s (passthrough: %v)\n", fn.Name.Value, fn.IsPassThrough))
		sBuilder.WriteString(fmt.Sprintf("TEXT ·_hike_%s(SB), %s, $%d-%d\n", fn.Name.Value, textFlag, 32, argSize))

		// 引数のロード (Go FP -> Win x64 レジスタ / スタック)
		for i, p := range fn.Params {
			offset := i * 8
			if i < len(winRegs) {
				sBuilder.WriteString(fmt.Sprintf("    MOVQ %s+%d(FP), %s\n", p.Name.Value, offset, winRegs[i]))
			} else {
				stackOffset := 32 + ((i - 4) * 8)
				sBuilder.WriteString(fmt.Sprintf("    MOVQ %s+%d(FP), AX\n", p.Name.Value, offset))
				sBuilder.WriteString(fmt.Sprintf("    MOVQ AX, %d(SP)\n", stackOffset))
			}
		}

		// Windows シャドウスペース確保 & 呼び出し
		sBuilder.WriteString("    SUBQ $32, SP\n")
		sBuilder.WriteString(fmt.Sprintf("    CALL %s(SB)\n", targetCName))
		sBuilder.WriteString("    ADDQ $32, SP\n")

		// 戻り値の退避 (RAX -> Go FP)
		if len(fn.ReturnTypes) > 0 {
			retOffset := len(fn.Params) * 8
			sBuilder.WriteString(fmt.Sprintf("    MOVQ AX, ret+%d(FP)\n", retOffset))
		}

		sBuilder.WriteString("    RET\n\n")
	}

	asmPath := filepath.Join(targetDir, "stub_windows_amd64.s")
	if err := os.WriteFile(asmPath, []byte(sBuilder.String()), 0644); err != nil {
		return fmt.Errorf("failed to write assembly stub: %w", err)
	}

	fmt.Printf("[hikec go] Successfully generated: %s\n", asmPath)
	return nil
}
