package compiler

import (
	"os"
	"path/filepath"
)

// GenerateWasmJSRuntime はメインスレッドとWeb Workerの両方を兼ねる統合 runtime.js を生成します
func GenerateWasmJSRuntime() string {
	return `/**
 * Hike Language Unified WebAssembly Runtime (runtime.js)
 * Auto-generated by hikec - Supports both Main Thread and Web Worker contexts.
 */

// モジュールスコープ変数: WASMが要求するヒープメモリサイズ (KB単位)
let heapSizeKB = 256;

// =============================================================================
// 1. Web Worker コンテキスト (WASM並行実行スレッド)
// =============================================================================
const isWorker = typeof importScripts === 'function' || 
                 (typeof window === 'undefined' && typeof self !== 'undefined' && typeof self.postMessage === 'function');

if (isWorker) {
    let wasmInstance = null;
    let sharedMemory = null;
    let nextEventId = 1;
    const eventStates = new Map();

    self.onmessage = async (e) => {
        const data = e.data;
        if (!data) return;

        // 外部APIからのヒープサイズ動的変更
        if (data.type === 'setHeapSizeKB') {
            heapSizeKB = Number(data.sizeKB);
            self.postMessage({
                type: 'log',
                message: ` + "`[Host/Worker] ヒープ容量設定が外部APIより変更されました: ${heapSizeKB} KB`" + `
            });
            return;
        }

        // 初期化および実行開始
        if (data.type === 'init') {
            const { wasmBytes, memory } = data;
            sharedMemory = memory;

            if (data.heapSizeKB) {
                heapSizeKB = Number(data.heapSizeKB);
            }

            const importObject = {
                env: {
                    memory: sharedMemory,

                    // --- WASM起動時メモリハンドシェイク ---
                    requestHeapSizeKB: () => {
                        self.postMessage({
                            type: 'log',
                            message: ` + "`[Host] WASMからのメモリ要求を受信: ${heapSizeKB} KB を許可`" + `
                        });
                        return heapSizeKB;
                    },

                    // --- DOM / UI コールバック ---
                    displayResult: (sum, mul) => {
                        self.postMessage({ type: 'result', sum: Number(sum), mul: Number(mul) });
                    },

                    // --- 32-bit 動的ヒープアロケータ ---
                    malloc: (size) => {
                        const mem = (wasmInstance && wasmInstance.exports && wasmInstance.exports.memory)
                                    ? wasmInstance.exports.memory
                                    : sharedMemory;

                        if (!self.heapOffset) {
                            if (wasmInstance && wasmInstance.exports && wasmInstance.exports.__heap_base) {
                                self.heapOffset = Number(wasmInstance.exports.__heap_base.value || wasmInstance.exports.__heap_base);
                            } else {
                                self.heapOffset = 65536; // 64KB
                            }
                        }

                        const ptr = self.heapOffset;
                        const allocSize = (Number(size) + 15) & ~15;
                        self.heapOffset += allocSize;

                        if (mem && self.heapOffset > mem.buffer.byteLength) {
                            const neededBytes = self.heapOffset - mem.buffer.byteLength;
                            const neededPages = Math.ceil(neededBytes / 65536);
                            try {
                                mem.grow(neededPages + 1);
                                self.postMessage({
                                    type: 'log',
                                    message: ` + "`[Host] WASMリニアメモリを拡張 (+${neededPages + 1} pages)`" + `
                                });
                            } catch (err) {
                                console.error("Failed to grow memory:", err);
                            }
                        }
                        return ptr;
                    },

                    calloc: (num, size) => {
                        const total = Number(num) * Number(size);
                        const ptr = importObject.env.malloc(total);
                        const mem = (wasmInstance && wasmInstance.exports && wasmInstance.exports.memory)
                                    ? wasmInstance.exports.memory
                                    : sharedMemory;
                        if (mem) {
                            new Uint8Array(mem.buffer, ptr, total).fill(0);
                        }
                        return ptr;
                    },

                    free: (ptr) => {},

                    // --- POSIX / WASM 抽象スレッド同期 API ---
                    hike_thread_spawn: (fnIdx, paramPtr) => {
                        const table = (wasmInstance && wasmInstance.exports)
                                      ? (wasmInstance.exports.__indirect_function_table || wasmInstance.exports.table)
                                      : null;
                        if (table) {
                            const thunk = table.get(fnIdx);
                            if (thunk) {
                                thunk(paramPtr);
                                return 0;
                            }
                        }
                        console.error("hike_thread_spawn: table or function index not found", fnIdx);
                        return -1;
                    },

                    hike_event_create: () => {
                        const id = nextEventId++;
                        eventStates.set(id, { signaled: false });
                        return id;
                    },

                    hike_event_signal: (eventId) => {
                        const ev = eventStates.get(eventId);
                        if (ev) ev.signaled = true;
                    },

                    hike_event_wait: (eventId, timeoutMs) => {
                        return 0;
                    },

                    hike_event_destroy: (eventId) => {
                        eventStates.delete(eventId);
                    },

                    hike_sleep_ms: (ms) => {
                        if (ms > 0 && sharedMemory) {
                            const i32 = new Int32Array(sharedMemory.buffer, 0, 1);
                            Atomics.wait(i32, 0, Atomics.load(i32, 0), Number(ms));
                        }
                    },

                    hike_now_ns: () => {
                        return BigInt(Math.floor(performance.now() * 1000000));
                    },

                    // 汎用スタブ
                    Sleep: (ms) => {},
                    GetTickCount64: () => BigInt(Date.now()),
                    QueueUserWorkItem: () => 0,
                    CreateEventA: () => 0,
                    SetEvent: () => 0,
                    WaitForSingleObject: () => 0,
                    CloseHandle: () => 0,
                    js_log: () => {},
                    js_set_text: () => {},
                    js_append_text: () => {},
                    js_set_badge_color: () => {}
                }
            };

            try {
                self.postMessage({ type: 'log', message: 'WASMモジュールをインスタンス化中...' });
                const { instance } = await WebAssembly.instantiate(wasmBytes, importObject);
                wasmInstance = instance;

                self.postMessage({ type: 'log', message: 'Hike main() を実行中...' });
                if (instance.exports.main) {
                    instance.exports.main(0, 0);
                }
            } catch (err) {
                self.postMessage({ type: 'log', message: 'ランタイム実行例外: ' + err });
            }
        }
    };
}

// =============================================================================
// 2. メインスレッド コンテキスト (ブラウザ DOM / クライアント側)
// =============================================================================
if (typeof window !== 'undefined') {
    class HikeConcurrentRuntime {
        /**
         * @param {Object} options
         * @param {string} [options.wasmUrl='main.wasm']
         * @param {string} [options.scriptUrl='runtime.js'] - 自身のスクリプトファイルパス
         * @param {number} [options.heapSizeKB=256]
         * @param {Function} [options.onResult]
         * @param {Function} [options.onLog]
         */
        constructor(options = {}) {
            this.wasmUrl = options.wasmUrl || 'main.wasm';
            this.scriptUrl = options.scriptUrl || 'runtime.js';
            this.heapSizeKB = options.heapSizeKB || 256;
            this.onResult = options.onResult || (() => {});
            this.onLog = options.onLog || (() => {});
            this.worker = null;
            this.memory = null;
            window.__hikeActiveRuntime = this;
        }

        /**
         * 外部からヒープサイズを変更するAPI
         */
        setHeapSizeKB(sizeKB) {
            this.heapSizeKB = Number(sizeKB);
            if (this.worker) {
                this.worker.postMessage({ type: 'setHeapSizeKB', sizeKB: this.heapSizeKB });
            }
        }

        getHeapSizeKB() {
            return this.heapSizeKB;
        }

        /**
         * runtime.js 自身を Worker として起動
         */
        async start() {
            this.onLog('Hike Concurrent Engine (runtime.js) を起動中...');

            // runtime.js 自体を Worker スレッドとしてインスタンス化
            this.worker = new Worker(this.scriptUrl + '?t=' + Date.now());

            this.worker.onmessage = (e) => {
                const { type, sum, mul, message } = e.data;
                if (type === 'log') {
                    this.onLog(message);
                } else if (type === 'result') {
                    this.onResult(sum, mul);
                }
            };

            this.memory = new WebAssembly.Memory({
                initial: 256,
                maximum: 512,
                shared: true
            });

            const res = await fetch(this.wasmUrl);
            if (!res.ok) {
                throw new Error(` + "`Failed to fetch WASM: ${res.statusText}`" + `);
            }
            const wasmBytes = await res.arrayBuffer();

            this.worker.postMessage({
                type: 'init',
                wasmBytes: wasmBytes,
                memory: this.memory,
                heapSizeKB: this.heapSizeKB
            });
        }

        terminate() {
            if (this.worker) {
                this.worker.terminate();
                this.worker = null;
            }
        }
    }

    // グローバル公開API
    window.HikeConcurrentRuntime = HikeConcurrentRuntime;
    window.setHikeHeapSizeKB = (sizeKB) => {
        heapSizeKB = Number(sizeKB);
        if (window.__hikeActiveRuntime) {
            window.__hikeActiveRuntime.setHeapSizeKB(heapSizeKB);
        }
    };
    window.getHikeHeapSizeKB = () => heapSizeKB;
}
`
}

// WriteWasmJSRuntime は指定されたパスへ runtime.js を書き出します
func WriteWasmJSRuntime(destPath string) error {
	dir := filepath.Dir(destPath)
	if dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return err
		}
	}
	code := GenerateWasmJSRuntime()
	return os.WriteFile(destPath, []byte(code), 0644)
}
