package compiler

import (
	"os"
	"path/filepath"
)

// GenerateWasmJSRuntime はブラウザおよび Node.js 用ランタイムブリッジ (runtime.js) のソースコード文字列を生成します
func GenerateWasmJSRuntime() string {
	return `/**
 * Hike Language WebAssembly Runtime Bridge
 * Auto-generated by hikec
 */
class HikeRuntime {
    constructor() {
        this.wasmInstance = null;
        this.memory = null;
        this.heapPtr = 65536; // スタック領域を避けて 64KB 以降をヒープ初期値とする
        this.textDecoder = new TextDecoder('utf-8');
        this.textEncoder = new TextEncoder();
    }

    // Wasm メモリ上のポインタと長さから JS 文字列を取得 (Number / BigInt 両対応)
    getString(ptr, len) {
        const p = Number(ptr);
        const l = Number(len);
        const bytes = new Uint8Array(this.memory.buffer, p, l);
        return this.textDecoder.decode(bytes);
    }

    // Wasm に渡すインポートオブジェクトの構築
    getImportObject() {
        return {
            env: {
                // --- 最小限のアロケータ実装 (Libc フリー) ---
                malloc: (size) => {
                    const s = Number(size);
                    const allocated = this.heapPtr;
                    this.heapPtr += (s + 7) & ~7; // 8 バイト境界アラインメント

                    // メモリ不足時は 64KB 単位でページ拡張
                    if (this.heapPtr > this.memory.buffer.byteLength) {
                        const neededPages = Math.ceil((this.heapPtr - this.memory.buffer.byteLength) / 65536);
                        this.memory.grow(neededPages);
                    }
                    return allocated;
                },
                calloc: (num, size) => {
                    const total = Number(num) * Number(size);
                    const ptr = this.getImportObject().env.malloc(total);
                    new Uint8Array(this.memory.buffer, ptr, total).fill(0);
                    return ptr;
                },
                free: (ptr) => {
                    // バンプアロケータのため即時解放はスキップ
                },

                // --- DOM & コンソール操作 API ---
                js_log: (ptr, len) => {
                    const msg = this.getString(ptr, len);
                    if (typeof document !== 'undefined') {
                        console.log(` + "`%c[Hike Wasm]%c ${msg}`, \"color: #3b82f6; font-weight: bold;\", \"color: inherit;\"" + `);
                    } else {
                        console.log(` + "`[Hike Wasm] ${msg}`" + `);
                    }
                },
                js_set_text: (idPtr, idLen, textPtr, textLen) => {
                    const id = this.getString(idPtr, idLen);
                    const text = this.getString(textPtr, textLen);
                    if (typeof document !== 'undefined') {
                        const el = document.getElementById(id);
                        if (el) el.innerText = text;
                    }
                },
                js_append_text: (idPtr, idLen, textPtr, textLen) => {
                    const id = this.getString(idPtr, idLen);
                    const text = this.getString(textPtr, textLen);
                    if (typeof document !== 'undefined') {
                        const el = document.getElementById(id);
                        if (el) el.innerText += text;
                    }
                },
                js_set_badge_color: (idPtr, idLen, colorPtr, colorLen) => {
                    const id = this.getString(idPtr, idLen);
                    const color = this.getString(colorPtr, colorLen);
                    if (typeof document !== 'undefined') {
                        const el = document.getElementById(id);
                        if (el) el.style.backgroundColor = color;
                    }
                },

                // シングルスレッド Wasm 向けのスタブ
                Sleep: (ms) => {},
                GetTickCount64: () => BigInt(Date.now()),
                QueueUserWorkItem: () => 0,
                CreateEventA: () => 0,
                SetEvent: () => 0,
                WaitForSingleObject: () => 0,
                CloseHandle: () => 0
            }
        };
    }

    // ブラウザ (fetch) と Node.js (fs) の両方に対応したユニバーサルローダー
    async load(wasmSource) {
        const importObject = this.getImportObject();
        let instance = null;

        const isNode = typeof process !== 'undefined' && process.versions != null && process.versions.node != null;

        if (isNode && typeof wasmSource === 'string') {
            const fs = await import('fs/promises');
            const buffer = await fs.readFile(wasmSource);
            const result = await WebAssembly.instantiate(buffer, importObject);
            instance = result.instance;
        } else if (typeof fetch === 'function' && typeof wasmSource === 'string') {
            if (typeof WebAssembly.instantiateStreaming === 'function') {
                try {
                    const response = await fetch(wasmSource);
                    const result = await WebAssembly.instantiateStreaming(response, importObject);
                    instance = result.instance;
                } catch (e) {
                    const response = await fetch(wasmSource);
                    const buffer = await response.arrayBuffer();
                    const result = await WebAssembly.instantiate(buffer, importObject);
                    instance = result.instance;
                }
            } else {
                const response = await fetch(wasmSource);
                const buffer = await response.arrayBuffer();
                const result = await WebAssembly.instantiate(buffer, importObject);
                instance = result.instance;
            }
        } else if (wasmSource instanceof ArrayBuffer || ArrayBuffer.isView(wasmSource)) {
            const result = await WebAssembly.instantiate(wasmSource, importObject);
            instance = result.instance;
        } else {
            throw new Error('[HikeRuntime] Unsupported wasm source format');
        }

        this.wasmInstance = instance;
        this.memory = instance.exports.memory || importObject.env.memory;

        // Wasm 側の InitApp 関数が存在すれば自動初期化
        if (typeof this.wasmInstance.exports.InitApp === 'function') {
            this.wasmInstance.exports.InitApp();
        }
        return this.wasmInstance.exports;
    }
}

// Node.js (CommonJS) 環境へのエクスポート対応
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { HikeRuntime };
}
`
}

// WriteWasmJSRuntime は指定されたパスへ runtime.js を書き出します
func WriteWasmJSRuntime(destPath string) error {
	dir := filepath.Dir(destPath)
	if dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return err
		}
	}
	code := GenerateWasmJSRuntime()
	return os.WriteFile(destPath, []byte(code), 0644)
}
